# version: '3.9'
# services:
#   apache:
#     image: httpd:latest
#     container_name: Portfolio_Wagner
#     ports:
#     - '5555:80'
#     volumes:
#     - .:/usr/local/apache2/htdocs
version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    container_name: php_container
    volumes:
      - ./src:/var/www/html

volumes:
  php-fpm-socket:
